version: '3.8'

services:
  database:
    container_name: database
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - os_handler_db:/data/db

volumes:
    os_handler_db:
    plots: