version: '3.8'

services:
  database:
    container_name: database
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - os_handler_db:/data/db

  client:
    container_name: "client"
    build: ./client/.
    volumes:
      - ./plots:/plots
    depends_on:
      - database

volumes:
    os_handler_db:
    plots: